ci:
  autoupdate_commit_msg: 'Bump `pre-commit` Dependency Versions'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args:
          - --fix
          - --unsafe-fixes
      # Does not have support for PEP 695 generics yet
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        name: mypy
        files: ^(?!(tests|changes)).*\.py$
        additional_dependencies:
          - aiorem ~= 0.0.2
          - aiostream ~= 0.7.0
          - httpx ~= 0.28.1
          - kurigram ~= 2.2.12
          - phonenumbers ~= 9.0.14
          - pydantic ~= 2.11.7
          - tgcrypto ~= 1.2.5
          - vobject~=0.9.9
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py312-plus
